week4/online-store/online_store/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :brands
  resources :categories
  resources :products

  root 'welcome#index'

end

week4/online-store/online_store/app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
end

week4/online-store/online_store/app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
end

week4/online-store/online_store/app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :brand, presence: true
  validates :category, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

week4/online-store/online_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week4/online-store/online_store/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def update
    @brand = Brand.find_by(params[:id])
    if @brand.update_attributes(brand_params)
      flash[:success] = 'Brand updated'
      redirect_to @brand
    else
      render 'edit'
    end
  end

  def show
    if params[:id]
      @brand = Brand.find_by(params[:id])
    else
      'nonexistent'
    end
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand
    else
      render 'new'
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :description)
  end
end

week4/online-store/online_store/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def update
    @category = Category.find_by(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = 'Category updated'
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show
    if params[:id]
      @category = Category.find_by(params[:id])
    else
      'nonexistent'
    end
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

week4/online-store/online_store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def update
    @product = Product.find_by(params[:id])

    if @product.update_attributes(product_params)
      flash[:success] = 'Product updated'
      redirect_to @product
    else
      render 'edit'
    end
  end

  def show
    if params[:id]
      @product = Product.find_by(params[:id])
    else
      'nonexistent'
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand, :category, :price, :quantity)
  end
end

week4/online-store/online_store/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

week4/online-store/online_store/app/helpers/application_helper.rb
module ApplicationHelper
end

week4/online-store/online_store/app/views/brands/_form.html.erb
<%= form_for @brand do |b|%>

  <% if @brand.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@brand.errors.count, 'error') %>
        prohibited this brand from being saved. 
      </h2>
      <ul>
        <%= @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= b.label :name %>
    <%= b.text_field :name %>
  </p>
  <p>
    <%= b.label :description %>
    <%= b.text_field :description %>
  </p>
  <p>
    <%= b.submit %>
  </p>
<% end %>

week4/online-store/online_store/app/views/brands/edit.html.erb
<h1>Edit brand</h1>

<%= render 'form' %>

<%= link_to 'Back to brands', brands_path %>

week4/online-store/online_store/app/views/brands/index.html.erb
<h1>Brands</h1>

<table>
  <tr>
    <td>ID:</td>
    <td>Name:</td>
    <td>Description:</td>
    <th colspan: 2></th>
  </tr>
  <% @brands.each do |brand| %>
    <tr>
      <td><%= brand.id %></td>
      <td><%= brand.name %></td>
      <td><%= brand.description %></td>
      <td><%= link_to 'Show', brand_path(brand) %></td>
      <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back to home', root_path %>
<%= link_to 'Create a new brand', new_brand_path %>

week4/online-store/online_store/app/views/brands/new.html.erb
<h1>Create a new brand</h1>

<%= render 'form' %>

<%= link_to 'Back to brands', brands_path %>

week4/online-store/online_store/app/views/brands/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @brand.description %>
</p>

<%= link_to 'Edit brand info', edit_brand_path %>
<%= link_to 'Back to brands', brands_path %>

week4/online-store/online_store/app/views/categories/_form.html.erb
<%= form_for @category do |c|%>

  <% if @category.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@category.errors.count, 'error') %>
        prohibited this category from being saved. 
      </h2>
      <ul>
        <%= @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= c.label :name %>
    <%= c.text_field :name %>
  </p>
  <p>
    <%= c.submit %>
  </p>
<% end %>

week4/online-store/online_store/app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= render 'form' %>

<%= link_to 'Back to categories', categories_path %>

week4/online-store/online_store/app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <tr>
    <td>ID:</td>
    <td>Name:</td>
    <th colspan: 2></th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= category.name %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back to home', root_path %>
<%= link_to 'Create a new category', new_category_path %>

week4/online-store/online_store/app/views/categories/new.html.erb
<h1>Create a new category</h1>

<%= render 'form' %>

<%= link_to 'Back to categories', categories_path %>

week4/online-store/online_store/app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit category info', edit_category_path %>
<%= link_to 'Back to categories', categories_path %>

week4/online-store/online_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week4/online-store/online_store/app/views/products/_form.html.erb
<%= form_for @product do |p|%>

  <% if @product.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@product.errors.count, 'error') %>
        prohibited this product from being saved. 
      </h2>
      <ul>
        <%= @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= p.label :name %>
    <%= p.text_field :name %>
  </p>
  <p>
    <%= p.label :brand %>
    <%= p.text_field :brand %>
  </p>
  <p>
    <%= p.label :category %>
    <%= p.text_field :category %>
  </p>
  <p>
    <%= p.label :price %>
    <%= p.number_field :price %>
  </p>
  <p>
    <%= p.label :quantity %>
    <%= p.number_field :quantity %>
  </p>
  <p>
    <%= p.submit %>
  </p>
<% end %>

week4/online-store/online_store/app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

<%= link_to 'Back to products', products_path %>

week4/online-store/online_store/app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <tr>
    <td>ID:</td>
    <td>Name:</td>
    <td>Brand:</td>
    <td>Category:</td>
    <td>Price:</td>
    <td>Quantity:</td>
    <th colspan: 2></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.brand %></td>
      <td><%= product.category %></td>
      <td><%= product.price %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back to home', root_path %>
<%= link_to 'Create a new product', new_product_path %>

week4/online-store/online_store/app/views/products/new.html.erb
<h1>Create a new product</h1>

<%= render 'form' %>

<%= link_to 'Back to products', products_path %>

week4/online-store/online_store/app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit product info', edit_product_path %>
<%= link_to 'Back to products', products_path %>

week4/online-store/online_store/app/views/welcome/index.html.erb
<h1>Online Store</h1>
<%= link_to 'Brands', brands_path%>
<%= link_to 'Categories', categories_path %>
<%= link_to 'Products', products_path %>